### ISSUE TITLE
Assertion `nr_pages' failed

### ISSUE THREAD

**Issue by tgrabiec** [cloudius-systems/seastar#54]
I've ran into the following assertion failure during startup of a server using seastar.

```
core/memory.cc:371: void memory::cpu_pages::free_span_no_merge(uint32_t, uint32_t): Assertion `nr_pages' failed.
```

```
gdb$ bt
#0  0x00007ffff4244cc9 in __GI_raise (sig=sig@entry=0x6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff42480d8 in __GI_abort () at abort.c:89
#2  0x00007ffff423db86 in __assert_fail_base (fmt=0x7ffff438e830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xe7425d "nr_pages", file=file@entry=0xe7424e "core/memory.cc", line=line@entry=0x173, function=function@entry=0xe745c0 <memory::cpu_pages::free_span_no_merge(unsigned int, unsigned int)::__PRETTY_FUNCTION__> "void memory::cpu_pages::free_span_no_merge(uint32_t, uint32_t)") at assert.c:92
#3  0x00007ffff423dc32 in __GI___assert_fail (assertion=0xe7425d "nr_pages", file=0xe7424e "core/memory.cc", line=0x173, function=0xe745c0 <memory::cpu_pages::free_span_no_merge(unsigned int, unsigned int)::__PRETTY_FUNCTION__> "void memory::cpu_pages::free_span_no_merge(uint32_t, uint32_t)") at assert.c:101
#4  0x00000000004d983c in memory::cpu_pages::free_span_no_merge (this=<optimized out>, span_start=<optimized out>, nr_pages=<optimized out>) at core/memory.cc:371
#5  0x00000000004d06de in ~temporary_buffer (this=0x7fffffffccd0, __in_chrg=<optimized out>) at ./core/temporary_buffer.hh:58
#6  apply (args=<unknown type in ..., CU 0x2e70f1, DIE 0x392847>, func=<unknown type in ..., CU 0x2e70f1, DIE 0x392835>) at core/apply.hh:34
#7  apply<file::dma_read_bulk(uint64_t, size_t)::<lambda(size_t)> mutable::<lambda()> mutable [with CharType = char]::<lambda(auto:10)>, temporary_buffer<char> > (args=<unknown type in ..., CU 0x2e70f1, DIE 0x367884>, func=<unknown type in ..., CU 0x2e70f1, DIE 0x367870>) at core/apply.hh:42
#8  apply<file::dma_read_bulk(uint64_t, size_t)::<lambda(size_t)> mutable::<lambda()> mutable [with CharType = char]::<lambda(auto:10)>, temporary_buffer<char> > (args=<unknown type in ..., CU 0x2e70f1, DIE 0x377c96>, func=<unknown type in ..., CU 0x2e70f1, DIE 0x377c83>) at core/future.hh:1083
#9  operator()<future_state<temporary_buffer<char> > > (state=<unknown type in ..., CU 0x2e70f1, DIE 0x37f08b>, __closure=0x600000e023a8) at core/future.hh:779
#10 _ZN12continuationIZN6futureII16temporary_bufferIcEEE4thenIZZZN4file13dma_read_bulkIcEES0_IIS1_IT_EEEmmENUlmE_clEmENUlvE0_clEvEUlS7_E_S0_IIEEEET0_OT_EUlOS7_E_IS2_EE3runEv (this=0x600000e02380) at core/future.hh:359
#11 0x000000000046f9f2 in reactor::run_tasks (this=0x7423, this@entry=0x6000001f1000, tasks=..., quota=0x6) at core/reactor.cc:1093
#12 0x000000000049650b in reactor::run (this=0x6000001f1000) at core/reactor.cc:1190
#13 0x00000000004e8c4a in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffd530, ac=ac@entry=0xd, av=av@entry=0x7fffffffd778, func=func@entry=<unknown type in ..., CU 0x5001c9, DIE 0x5a7095>) at core/app-template.cc:122
#14 0x000000000041dd62 in main (ac=0xd, av=0x7fffffffd778) at main.cc:279
```

**Comment by tgrabiec** [comment]
Closing as it turned out to be a memory corruption not caused by the seastar framework.
